Unit test fixes for Windows
dotnet/format pull request #1804
Opened 2023-02-28 22:55 UTC by seriouz

I've made some changes to the unit tests, so that they are all working with windows.
Almost all changes regarded the end-of-line problem between Windows and Linux/Mac.

2023-02-28 22:56 UTC, seriouz commented
@dotnet-policy-service agree

2023-03-10 18:26 UTC, RikkiGibson commented
Windows tests runs are timing out here.

Also seeing a warning in the test project: `/home/vsts/work/1/s/tests/Formatters/OrganizeImportsFormatterTests.cs(3,1): warning IDE0005: Using directive is unnecessary. [/home/vsts/work/1/s/tests/dotnet-format.UnitTests.csproj]`

2023-04-19 19:49 UTC, JoeRobich commented
Not sure why these changes would be necessary.

2023-04-26 13:28 UTC, sharwell requested changes
In general this isn't the approach we'd want to go with for normalizing the tests. I'll need to review the variety of changes individually to discuss the resolution plan.

2023-04-26 13:33 UTC, sharwell reviewed
I suspect the author of this pull request might have not set `core.autocrlf=true` on a Windows machine, which would lead to expected failures. Prior to any fixes, please verify that the local configuration is correct.

2023-04-26 13:33 UTC, sharwell commented on tests/Analyzers/ThirdPartyAnalyzerFormatterTests.cs
> +        count = 6;
❔ Why was this added?

2023-04-26 13:33 UTC, sharwell commented on tests/Analyzers/ThirdPartyAnalyzerFormatterTests.cs
> +                ["end_of_line"] = EndOfLineFormatter.GetEndOfLineOption("\n"),
❔ Why was this added?

2023-04-26 13:33 UTC, sharwell commented on tests/Analyzers/ThirdPartyAnalyzerFormatterTests.cs
> +                ["end_of_line"] = EndOfLineFormatter.GetEndOfLineOption("\n"),
❔ Why was this added? This test has `expectedCode` that relies on the environment newline, and the default `end_of_line` value would be the same. This test wouldn't have been failing before this change, provided the user on Windows checked out the code with the _required_ `core.autocrlf=true` configuration.

2023-04-26 13:33 UTC, sharwell commented on tests/CodeFormatterTests.cs
> +            var expectedPublicApi = sb.ToString();
❔ Why was this changed?

2023-04-26 13:33 UTC, sharwell commented on tests/Formatters/OrganizeImportsFormatterTests.cs
> +                ["end_of_line"] = EndOfLineFormatter.GetEndOfLineOption("\n"),
❔ Why was this changed? Applies to all instances of this in the file.

2024-05-07 06:58 UTC, JoeRobich commented
Closing as 9.x development has moved into the dotnet/sdk repo.

2024-05-07 06:58 UTC, closed without merging